<div class="container-fluid">
    <div>
        <h3>التكوين العام</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">الرئسية</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">إعدادات</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">التكوين العام</li>
            </ol>
        </nav>
    </div>
    <?php $getStatus = getStatus(); if (!empty($getStatus) && !empty(checkIfThereIsError($getStatus))) {?><div class="alert alert-danger"><strong>Important!</strong> There are some errors found on your system, please review <a href="<?php echo Wo_LoadAdminLinkSettings('system_status'); ?>" data-ajax="?path=system_status">System Status</a>.</div><?php }?>
    <!-- Vertical Layout -->
    <?php if ($wo['config']['website_mode'] != 'facebook') { ?>
        <div class="alert alert-warning">ملاحظة: يتم تعطيل بعض الميزات بسبب وضع موقع الويب الذي استخدمته.</div>
    <?php } ?>
    <div class="row">
        <div class="col-lg-6 col-md-6 float-left">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">التكوين العام</h6>
                    <form class="general-settings" method="POST">
                        <div class="float-left">
                            <label for="developer_mode" class="main-label">وضع المطور</label>
                            <br><small class="admin-info">من خلال تمكين وضع المطور ، سيتم تمكين الإبلاغ عن الخطأ ، <br> لا ينصح بتمكين هذا الوضع دون مساعدة من مطور ، <br> قد يحدث هذا في بعض المشكلات في موقع الويب الخاص بك.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="developer_mode" value="0" />
                            <input type="checkbox" name="developer_mode" id="chck-developer_mode" value="1" <?php echo ($wo['config']['developer_mode'] == 1) ? 'checked': '';?>>
                            <label for="chck-developer_mode" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="cacheSystem" class="main-label">نظام التخزين المؤقت</label>
                            <br><small class="admin-info">من خلال تمكين نظام ذاكرة التخزين المؤقت ، قم بتسريع موقع الويب الخاص بك إلى 80 ٪! <br> ملاحظة: يجب تعيين ذاكرة التخزين المؤقت المجلد وجميع إذن المجلد الفرعي إلى 777.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="cacheSystem" value="0" />
                            <input type="checkbox" name="cacheSystem" id="chck-cacheSystem" value="1" <?php echo ($wo['config']['cacheSystem'] == 1) ? 'checked': '';?>>
                            <label for="chck-cacheSystem" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="maintenance_mode" class="main-label">نمط الصيانة</label>
                            <br><small class="admin-info">اقلب الموقع بأكمله تحت الصيانة. <br> يمكنك استعادة الموقع من خلال الزيارة /ADMINCP أو /admin</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="maintenance_mode" value="0" />
                            <input type="checkbox" name="maintenance_mode" id="chck-maintenance_mode" value="1" <?php echo ($wo['config']['maintenance_mode'] == 1) ? 'checked': '';?>>
                            <label for="chck-maintenance_mode" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="useSeoFrindly" class="main-label">SEO url ودية</label>
                            <br><small class="admin-info">تمكين التحميل السلس لحفظ النطاق الترددي.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="useSeoFrindly" value="0" />
                            <input type="checkbox" name="useSeoFrindly" id="chck-useSeoFrindly" value="1" <?php echo ($wo['config']['useSeoFrindly'] == 1) ? 'checked': '';?>>
                            <label for="chck-useSeoFrindly" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="developers_page" class="main-label">المطورين (نظام API)</label>
                            <br><small class="admin-info">عرض /مطورون صفحة لجميع المستخدمين لطلبات API.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="developers_page" value="0" />
                            <input type="checkbox" name="developers_page" id="chck-developers_page" value="1" <?php echo ($wo['config']['developers_page'] == 1) ? 'checked': '';?>>
                            <label for="chck-developers_page" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="profile_privacy" class="main-label">ترحيب مستخدمي الصفحة</label>
                            <br><small class="admin-info">السماح للمستخدمين غير المسجلين بعرض ملفات تعريف المستخدم على صفحة الترحيب.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="profile_privacy" value="0" />
                            <input type="checkbox" name="profile_privacy" id="chck-profile_privacy" value="1" <?php echo ($wo['config']['profile_privacy'] == 1) ? 'checked': '';?>>
                            <label for="chck-profile_privacy" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <label for="defualtLang" class="main-label">اللغة الافتراضية</label>
                        <br><small class="admin-info">اضبط لغة موقعك الافتراضية.</small>
                        <div class="form-group">
                            <select class="form-control show-tick" id="defualtLang" name="defualtLang">
                                <?php
                                 foreach (Wo_LangsNamesFromDB() as $lang) {
                                    
                                   $languages = $lang;
                                    
                                   $languages_name = ucfirst(strtolower($languages));
                                    
                                   $selected_lang = ($languages == $wo['config']['defualtLang']) ? ' selected' : '';
                                    
                                 ?>
                              <option value="<?php echo $languages;?>"<?php echo $selected_lang;?> ><?php echo $languages_name;?></option>
                              <?php } ?>
                            </select>
                        </div>
                        <hr>
                        <label for="date_style" class="main-label">صيغة التاريخ</label>
                        <br><small class="admin-info">اضبط تنسيق تاريخ موقعك الافتراضي.</small>
                        <select class="form-control show-tick" id="date_style" name="date_style">
                          <option value="m-d-y" <?php if($wo['config']['date_style'] == 'm-d-y'){echo 'selected';};?> >mm-dd-yy</option>
                          <option value="d-m-y" <?php if($wo['config']['date_style'] == 'd-m-y'){echo 'selected';};?> >dd-mm-yy</option>
                          <option value="y-m-d" <?php if($wo['config']['date_style'] == 'y-m-d'){echo 'selected';};?> >yy-mm-dd</option>
                          <option value="M-d-y" <?php if($wo['config']['date_style'] == 'M-d-y'){echo 'selected';};?> >mmm-dd-yy</option>      
                          <option value="d-F-y" <?php if($wo['config']['date_style'] == 'd-F-y'){echo 'selected';};?> >dd-mmmm-yy</option>
                          <option value="Y-m-d" <?php if($wo['config']['date_style'] == 'Y-m-d'){echo 'selected';};?> >yyyy-mm-dd</option> 
                          <option value="d-M-Y" <?php if($wo['config']['date_style'] == 'd-M-Y'){echo 'selected';};?> >dd-mmm-yyyy</option>
                          <option value="d-F-Y" <?php if($wo['config']['date_style'] == 'd-F-Y'){echo 'selected';};?> >dd-mmmm-yyyy</option>
                        </select>
                        <hr>

                        <label for="directory_landing_page">الصفحة المقصودة</label>
                        <select class="form-control show-tick" id="directory_landing_page" name="directory_landing_page">
                          <option value="welcome" <?php echo ($wo['config']['directory_landing_page'] == 'welcome')   ? ' selected' : '';?> >صفحة تسجيل الدخول</option>
                          <option value="register" <?php echo ($wo['config']['directory_landing_page'] == 'register')   ? ' selected' : '';?> >صفحة التسجيل</option>
                          <option value="home" <?php echo ($wo['config']['directory_landing_page'] == 'home')   ? ' selected' : '';?> >صفحة أخبار</option>
                          <option value="directory" <?php echo ($wo['config']['directory_landing_page'] == 'directory')   ? ' selected' : '';?> >صفحة الدليل</option>
                        </select>
                        <small class="admin-info">إذا لم يتم تسجيل الأشخاص ، فسيتم إعادة توجيههم إلى هذه الصفحة.</small>
                        
                        <!-- <div class="general-settings-alert"></div> -->
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <!-- <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button> -->
                    </form>
                </div>
            </div>
              <div class="card">
                <div class="card-body">
                    <h6 class="card-title">تكوين المستخدم</h6>
                    <form class="user2-settings" method="POST">
                        <div class="float-left">
                            <label for="online_sidebar" class="main-label">مستخدمين على الهواء</label>
                        <br><small class="admin-info">إظهار المستخدمين النشطين الحاليين في الصفحة الرئيسية.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="online_sidebar" value="0" />
                            <input type="checkbox" name="online_sidebar" id="chck-online_sidebar" value="1" <?php echo ($wo['config']['online_sidebar'] == 1) ? 'checked': '';?>>
                            <label for="chck-online_sidebar" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="user_lastseen" class="main-label">آخر مرة رأى المستخدم حالة</label>
                           <br><small class="admin-info">السماح للمستخدمين بتعيين حالتهم ، عبر الإنترنت وآخر نشط.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="user_lastseen" value="0" />
                            <input type="checkbox" name="user_lastseen" id="chck-user_lastseen" value="1" <?php echo ($wo['config']['user_lastseen'] == 1) ? 'checked': '';?>>
                            <label for="chck-user_lastseen" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="deleteAccount" class="main-label">حذف حساب المستخدم</label>
                            <br><small class="admin-info">السماح للمستخدمين بحذف حساباتهم.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="deleteAccount" value="0" />
                            <input type="checkbox" name="deleteAccount" id="chck-deleteAccount" value="1" <?php echo ($wo['config']['deleteAccount'] == 1) ? 'checked': '';?>>
                            <label for="chck-deleteAccount" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="profile_back" class="main-label">تغيير خلفية الملف الشخصي</label>
                            <select class="form-control show-tick" id="profile_background_request" name="profile_background_request" onchange="SelectProModel('can_use_background',this)">
                              <option value="admin" <?php echo ($wo['config']['profile_background_request'] == 'admin')   ? ' selected' : '';?> ><svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"> <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path> <circle cx="12" cy="7" r="4"></circle> </svg>مسؤل</option>
                              <option value="all" <?php echo ($wo['config']['profile_background_request'] == 'all')   ? ' selected' : '';?> ><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe"> <circle cx="12" cy="12" r="10"></circle> <line x1="2" y1="12" x2="22" y2="12"></line> <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path> </svg> جميع المستخدمين</option>
                              <option value="verified" <?php echo ($wo['config']['profile_background_request'] == 'verified')   ? ' selected' : '';?> ><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="verified-color feather feather-check-circle" title="" data-toggle="tooltip" data-original-title="Verified User"><path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z"></path></svg>تم التحقق من المستخدمين فقط</option>
                              <option value="pro" <?php echo ($wo['config']['profile_background_request'] == 'pro')   ? ' selected' : '';?> ><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7,2V13H10V22L17,10H13L17,2H7Z"></path></svg>المستخدمين المحترفين فقط</option>
                            </select>
                            <br><small class="admin-info">السماح للمستخدمين بتغيير خلفيات ملفهم الشخصي عن طريق تحميل صورة.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="profile_back" value="0" />
                            <input type="checkbox" name="profile_back" id="chck-profile_back" value="1" <?php echo ($wo['config']['profile_back'] == 1) ? 'checked': '';?>>
                            <label for="chck-profile_back" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                         <div class="float-left">
                            <label for="connectivitySystem" class="main-label">نظام الأصدقاء</label>
                        <br><small class="admin-info">اختر بين متابعة ونظام الأصدقاء. <br> <span style = "color: #c48a36"> إذا قمت بتغيير النظام إلى نظام آخر ، يتم حذف جميع المتابعين الحاليين ، والأصدقاء.</span></small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="connectivitySystem" value="0" />
                            <input type="checkbox" name="connectivitySystem" id="chck-connectivitySystem" value="1" <?php echo ($wo['config']['connectivitySystem'] == 1) ? 'checked': '';?>>
                            <label for="chck-connectivitySystem" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group">
                            <div class="form-line">
                                <label class="form-label" class="main-label">حد نظام الاتصال</label>
                                <input type="text" name="connectivitySystemLimit" class="form-control" value="<?php echo $wo['config']['connectivitySystemLimit']?>"><small class="admin-info">كم عدد الأصدقاء يمكن أن يكون كل مستخدم؟</small>
                            </div>
                        </div>
                        <hr>
                        
                         <div class="float-left">
                            <label for="invite_links_system" class="main-label">نظام دعوة المستخدم</label>
                            <br><small class="admin-info">السماح للمستخدمين بدعوة المستخدمين الآخرين إلى موقعك.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="invite_links_system" value="0" />
                            <input type="checkbox" name="invite_links_system" id="chck-invite_links_system" value="1" <?php echo ($wo['config']['invite_links_system'] == 1) ? 'checked': '';?>>
                            <label for="chck-invite_links_system" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <label class="form-label" class="main-label">كم عدد الروابط التي يمكن للمستخدم إنشاءها؟</label>
                            <div class="form-line">
                                <input type="text" id="user_links_limit" name="user_links_limit" class="form-control" value="<?php echo $wo['config']['user_links_limit']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <label class="form-label" class="main-label">يمكن للمستخدم إنشاء روابط X داخل؟</label>
                            <div class="form-line">
                                <select class="form-control show-tick" id="expire_user_links" name="expire_user_links">
                                      <option value="hour" <?php echo ($wo['config']['expire_user_links'] == 'hour')   ? ' selected': '';?>>1 ساعة</option>
                                      <option value="day" <?php echo ($wo['config']['expire_user_links'] == 'day')   ? ' selected': '';?>>يوم 1</option>
                                      <option value="week" <?php echo ($wo['config']['expire_user_links'] == 'week')   ? ' selected': '';?>>1 أسبوع</option>
                                      <option value="month" <?php echo ($wo['config']['expire_user_links'] == 'month')   ? ' selected': '';?>>1 شهر</option>
                                      <option value="year" <?php echo ($wo['config']['expire_user_links'] == 'year')   ? ' selected': '';?>>1 سنة</option>
                                </select>
                            </div>
                        </div>
                        <!-- <div class="user2-settings-alert"></div> -->
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <!-- <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button> -->
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">اعدادات اخرى</h6>
                    <div class="other-settings-alert"></div>
                    <form class="other-settings" method="POST">
                        <div class="form-group form-float">
                            <label class="form-label">الكلمات الخاضعة للرقابة</label>
                            <div class="form-line">
                                <input type="text" id="censored_words" name="censored_words" class="form-control" value="<?php echo $wo['config']['censored_words']?>">
                                <small class="admin-info">الكلمات التي سيتم الرقابة واستبدالها بـ *** في الرسائل والمنشورات والتعليقات وما إلى ذلك ، مفصولة بفاصلة.</small>
                            </div>
                        </div>
                        <label for="cache_sidebar" >الصفحة الرئيسية التخزين المؤقت</label>
                        <select class="form-control show-tick" id="cache_sidebar" name="cache_sidebar">
                          <option value="1" <?php echo ($wo['config']['cache_sidebar'] == 1)   ? ' selected' : '';?> >قم بتحديث بيانات الشريط الجانبي للصفحة الرئيسية كل دقيقتين (تحميل أسرع)</option>
                          <option value="0" <?php echo ($wo['config']['cache_sidebar'] == 0)   ? ' selected' : '';?> >لا تقم أبدًا بتخزين ذاكرة التخزين المؤقت ، دائمًا إحضار بيانات جديدة</option>
                        </select>
                        <small class="admin-info">قم بتمكين هذه الميزة من حفظ استخدام MySQL وزيادة سرعة الصفحة الرئيسية. </small>
                        <div class="clearfix"></div>
                        <label for="update_user_profile" >التخزين المؤقت لصفحة الملف الشخصي</label>
                        <div class="form-group">
                            <select class="form-control show-tick" id="update_user_profile" name="update_user_profile">
                              <option value="30" <?php echo ($wo['config']['update_user_profile'] == 30)   ? ' selected' : '';?> >كل 30 ثانية</option>
                              <option value="120" <?php echo ($wo['config']['update_user_profile'] == 120)   ? ' selected' : '';?> >كل دقيقتين</option>
                              <option value="3600" <?php echo ($wo['config']['update_user_profile'] == 3600)   ? ' selected' : '';?> >كل ساعة</option>
                              <option value="7200" <?php echo ($wo['config']['update_user_profile'] == 7200)   ? ' selected' : '';?> >كل ساعتين</option>
                              <option value="43200" <?php echo ($wo['config']['update_user_profile'] == 43200)   ? ' selected' : '';?> >كل 12 ساعة</option>
                              <option value="86400" <?php echo ($wo['config']['update_user_profile'] == 86400)   ? ' selected' : '';?> >كل 24 ساعة</option>
                            </select>
                            <small class="admin-info margin-top-5">تحديث بيانات الشريط الجانبي كل X ، وهذا يرتبط بنظام ذاكرة التخزين المؤقت لحفظ استخدام MySQL.</small>
                        </div>
                        <div class="form-group form-float">
                            <label class="form-label">تبادل مفتاح API</label>
                            <div class="form-line">
                                <input type="text" id="exchangerate_key" name="exchangerate_key" class="form-control" value="<?php echo $wo['config']['exchangerate_key']?>">
<small class = "admin-info"> مفتاح واجهة برمجة تطبيقات تبادلك من <a href="https://app.exchangerate-api.com/dashboard"> هنا </a> </small>                            </div>
                        </div>
                        <hr>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            
        </div>
        <div class="col-lg-6 col-md-6 float-right">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">تسجيل الدخول والتسجيل</h6>
                    <form class="user-settings" method="POST">
                        <div class="float-left">
                            <label for="user_registration" class="main-label">تسجيل المستخدم</label>
                            <br><small class="admin-info">السماح للمستخدمين بإنشاء حسابات في موقعك.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="user_registration" value="0" />
                            <input type="checkbox" name="user_registration" id="chck-user_registration" value="1" <?php echo ($wo['config']['user_registration'] == 1) ? 'checked': '';?>>
                            <label for="chck-user_registration" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="auto_username" class="main-label">Auto Username On Register</label>
                            <br><small class="admin-info">Generate an auto username on sign up. <br> Registration form will ask for user's first name and last name.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="auto_username" value="0" />
                            <input type="checkbox" name="auto_username" id="chck-auto_username" value="1" <?php echo ($wo['config']['auto_username'] == 1) ? 'checked': '';?>>
                            <label for="chck-auto_username" class="check-trail"><span class="check-handler"></span></label>
                        </div> 
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="password_complexity_system" class="main-label">Password Complexity System</label>
                            <br><small class="admin-info">The system will require a powerful password on sign up, <br>including letters, numbers and special characters.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="password_complexity_system" value="0" />
                            <input type="checkbox" name="password_complexity_system" id="chck-password_complexity_system" value="1" <?php echo ($wo['config']['password_complexity_system'] == 1) ? 'checked': '';?>>
                            <label for="chck-password_complexity_system" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="login_auth" class="main-label">Unusual Login</label>
                            <br><small class="admin-info">Send a confirmation link when the user login from a new location.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="login_auth" value="0" />
                            <input type="checkbox" name="login_auth" id="chck-login_auth" value="1" <?php echo ($wo['config']['login_auth'] == 1) ? 'checked': '';?>>
                            <label for="chck-login_auth" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="remember_device" class="main-label">Remember This Device</label>
                            <br><small class="admin-info">Remember this device in welcome page.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="remember_device" value="0" />
                            <input type="checkbox" name="remember_device" id="chck-remember_device" value="1" <?php echo ($wo['config']['remember_device'] == 1) ? 'checked': '';?>>
                            <label for="chck-remember_device" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="login_auth" class="main-label">Two-factor authentication</label>
                            <br><small class="admin-info">Send confirmation code to email or SMS when user login.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="two_factor" value="0" />
                            <input type="checkbox" name="two_factor" id="chck-two_factor" value="1" <?php echo ($wo['config']['two_factor'] == 1) ? 'checked': '';?>>
                            <label for="chck-two_factor" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <label for="defualtLang">Two-factor Authentication Method</label>
                        <br><small class="admin-info">Select the system the 2FA should use.</small>
                        <div class="form-group">
                            <select class="form-control show-tick" id="two_factor_type" name="two_factor_type">
                              <option value="email" <?php echo ($wo['config']['two_factor_type'] == 'email') ? 'selected': '';?>>E-mail Address</option>
                              <option value="phone" <?php echo ($wo['config']['two_factor_type'] == 'phone') ? 'selected': '';?>>SMS / Phone Number</option>
                              <option value="both" <?php echo ($wo['config']['two_factor_type'] == 'both') ? 'selected': '';?>>Both Together</option>
                            </select>
                        </div>
                        <hr>
                        <div class="float-left">
                            <label for="google_authenticator" class="main-label">Google Authenticator Settings</label>
                            <br><small class="admin-info">Google Authenticator code when user login.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="google_authenticator" value="0" />
                            <input type="checkbox" name="google_authenticator" id="chck-google_authenticator" value="1" <?php echo ($wo['config']['google_authenticator'] == '1') ? 'checked': '';?>>
                            <label for="chck-google_authenticator" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="authy_settings" class="main-label">Authy Settings</label>
                            <br><small class="admin-info">Authy code when user login.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="authy_settings" value="0" />
                            <input type="checkbox" name="authy_settings" id="chck-authy_settings" value="1" <?php echo ($wo['config']['authy_settings'] == '1') ? 'checked': '';?>>
                            <label for="chck-authy_settings" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Authy Token</label>
                                <input type="text" id="authy_token" name="authy_token" class="form-control" value="<?php echo $wo['config']['authy_token'] ?>">
                                <small class="admin-info">Authy Token from your twilio account</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="emailValidation" class="main-label">Account Validation</label>
                            <br><small class="admin-info">Send an activation link after registration.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="emailValidation" value="0" />
                            <input type="checkbox" name="emailValidation" id="chck-emailValidation" value="1" <?php echo ($wo['config']['emailValidation'] == 1) ? 'checked': '';?>>
                            <label for="chck-emailValidation" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <label for="defualtLang" >Account Validation Method</label>
                        <br><small class="admin-info">Choose the validation type, by SMS or E-mail, if you choose SMS, <br> make sure you have configured SMS.</small>
                        <div class="form-group">
                            <select class="form-control show-tick" id="sms_or_email" name="sms_or_email">
                                <option value="mail" <?php echo ($wo['config']['sms_or_email'] == 'mail') ? 'selected': '';?>>E-mail address</option>
                                <option value="sms" <?php echo ($wo['config']['sms_or_email'] == 'sms') ? 'selected': '';?>>SMS / Phone Number</option>
                            </select>
                        </div>
                        <hr>
                        <div class="float-left">
                            <label for="reCaptcha" class="main-label">reCaptcha</label>
                            <br><small class="admin-info">Enable reCaptcha to prevent spam.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="reCaptcha" value="0" />
                            <input type="checkbox" name="reCaptcha" id="chck-reCaptcha" value="1" <?php echo ($wo['config']['reCaptcha'] == 1) ? 'checked': '';?>>
                            <label for="chck-reCaptcha" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Recaptcha Key</label>
                                <input type="text" id="reCaptchaKey" name="reCaptchaKey" class="form-control" value="<?php echo $wo['config']['reCaptchaKey']?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Recaptcha Secret Key</label>
                                <input type="text" id="recaptcha_secret_key" name="recaptcha_secret_key" class="form-control" value="<?php echo $wo['config']['recaptcha_secret_key']?>">
                            </div>
                        </div>
                        <hr>
                        <div class="float-left">
                            <label for="reCaptcha" class="main-label">Prevent Bad Login Attempts</label>
                            <br><small class="admin-info">Enable this feature to track and stop brute-force attacks.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="prevent_system" value="0" />
                            <input type="checkbox" name="prevent_system" id="chck-prevent_system" value="1" <?php echo ($wo['config']['prevent_system'] == 1) ? 'checked': '';?>>
                            <label for="chck-prevent_system" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Login Limit</label>
                                <input type="text" id="bad_login_limit" name="bad_login_limit" class="form-control" value="<?php echo $wo['config']['bad_login_limit']?>">
                                <small class="admin-info">How many times a user can try to login before a lockout?</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Lockout Time (In Minutes)</label>
                                <input type="text" id="lock_time" name="lock_time" class="form-control" value="<?php echo $wo['config']['lock_time']?>">
                                <small class="admin-info">For how long should the user stay locked out?</small>
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-float">
                            <label for="user_limit" class="main-label">Registration Limits</label>
                            <small class="admin-info">How many times a user can create accounts per hour.</small>
                            <div class="form-line">
                                <input type="text" id="user_limit" name="user_limit" class="form-control" value="<?php echo $wo['config']['user_limit']?>">
                                
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <hr>

                        <div class="float-left">
                            <label for="reserved_usernames_system" class="main-label">Reserved usernames System</label>
                            <br><small class="admin-info">Reserved usernames System</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="reserved_usernames_system" value="0" />
                            <input type="checkbox" name="reserved_usernames_system" id="chck-reserved_usernames_system" value="1" <?php echo ($wo['config']['reserved_usernames_system'] == '1') ? 'checked': '';?>>
                            <label for="chck-reserved_usernames_system" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Reserved usernames</label>
                                <textarea name="reserved_usernames" class="form-control"><?php echo ($wo['config']['reserved_usernames']);?></textarea>
                                <small class="admin-info">Reserved usernames</small>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="disable_start_up" class="main-label">Disable start page</label>
                            <br><small class="admin-info">Disable start up page</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="disable_start_up" value="0" />
                            <input type="checkbox" name="disable_start_up" id="chck-disable_start_up" value="1" <?php echo ($wo['config']['disable_start_up'] == '1') ? 'checked': '';?>>
                            <label for="chck-disable_start_up" class="check-trail"><span class="check-handler"></span></label>
                        </div>

                        <!-- <div class="user-settings-alert"></div> -->
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <!-- <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button> -->
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Notifications Settings</h6>
                    <form class="notifications-settings" method="POST">
                        <div class="float-left">
                            <label for="emailNotification" class="main-label">E-mail Notifications </label>
                            <br><small class="admin-info">Send E-mail notifications to users after getting site notifications.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="emailNotification" value="0" />
                            <input type="checkbox" name="emailNotification" id="chck-emailNotification" value="1" <?php echo ($wo['config']['emailNotification'] == 1) ? 'checked': '';?>>
                            <label for="chck-emailNotification" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="profileVisit" class="main-label">Profile Visit Notifications </label>
                            <br><small class="admin-info">Send a notification to a user when someone visits his profile. <br>Note that this feature will require the user to become a Pro member if you enable Pro System.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="profileVisit" value="0" />
                            <input type="checkbox" name="profileVisit" id="chck-profileVisit" value="1" <?php echo ($wo['config']['profileVisit'] == 1) ? 'checked': '';?>>
                            <label for="chck-profileVisit" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="float-left">
                            <label for="notify_new_post" class="main-label">Notification On New Post</label>
                            <br><small class="admin-info">Send a notification to followers when a user creates a new post.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="notify_new_post" value="0" />
                            <input type="checkbox" name="notify_new_post" id="chck-notify_new_post" value="1" <?php echo ($wo['config']['notify_new_post'] == 1) ? 'checked': '';?>>
                            <label for="chck-notify_new_post" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>

                        <!--  <div class="notifications-settings-alert"></div> -->
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>"><!-- 
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button> -->
                    </form>
                </div>
            </div>
            
            
        </div> 
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>

$(function() {
    $('.switcher input[type=checkbox]').click(function () {
        setToTrue = 0;
        if ($(this).is(":checked") === true) {
            setToTrue = 1;
        }
        var configName = $(this).attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = setToTrue;
        objData['hash_id'] = hash_id;
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData);
    });

    var setTimeOutColor = setTimeout(function (){});
    $('select').on('change', function() {
         clearTimeout(setTimeOutColor);
        var thisElement = $(this);
        var configName = thisElement.attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = this.value;
        objData['hash_id'] = hash_id;
        thisElement.addClass('warning');
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
            if (data.status == 200) {
                thisElement.removeClass('warning');
                thisElement.addClass('success');
            } else {
                thisElement.addClass('error');
            }
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('success');
                thisElement.removeClass('warning');
                thisElement.removeClass('error');
            }, 2000);
        });
    });
    $('input[type=text], input[type=number] , textarea').on('input', delay(function() {
            clearTimeout(setTimeOutColor);
            var thisElement = $(this);
            var configName = thisElement.attr('name');
            var hash_id = $('input[name=hash_id]').val();
            var objData = {};
            objData[configName] = this.value;
            objData['hash_id'] = hash_id;
            thisElement.addClass('warning');
            $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
                if (data.status == 200) {
                    thisElement.removeClass('warning');
                    thisElement.addClass('success');
                } else {
                    thisElement.addClass('error');
                }
                var setTimeOutColor = setTimeout(function () {
                    thisElement.removeClass('success');
                    thisElement.removeClass('warning');
                    thisElement.removeClass('error');
                }, 2000);
                //thisElement.focus();
            });
    }, 500));
});

</script>